name: CI - build and test

on:                                
  push:
    branches: [ main, gh-pages]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew              
    - name: Build and test
      working-directory: ./project
      timeout-minutes: 20
      run: ../gradlew build
    - name: Deploy
        uses: andrew153d/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build/reports
      